config/routes.rb
Rails.application.routes.draw do
  resources :dogs
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dog.rb
class Dog < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController
  def index
    @dogs = Dog.all
  end

  def show
    @dog = Dog.find(params[:id])
  end

  def create
    dog = Dog.create(dog_params)
    redirect_to dogs_path
  end

  def new
    @dog = Dog.new
  end

  def edit
    @dog = Dog.find(params[:id])
  end

  def update
    @dog = Dog.find(params[:id])
    @dog.update(dog_params)
    redirect_to dog_path(@dog)
  end

  def destroy
    @dog = Dog.find(params[:id])
    @dog.destroy
    redirect_to dogs_path
  end

  private
  def dog_params
    params.require(:dog).permit(:name, :motto)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dogs_helper.rb
module DogsHelper
end

app/views/dogs/create.html.erb
<h1>Dogs#create</h1>
<p>Find me in app/views/dogs/create.html.erb</p>

app/views/dogs/edit.html.erb
<h1>Dogs#edit</h1>
<p>Find me in app/views/dogs/edit.html.erb</p>
<h1><%= @dog.name %></h1>
<%= form_with model: @dog do |f| %>
  <%= f.text_field :name %>
  <%= f.text_field :motto %>
  <%= f.submit %>
<% end %>

app/views/dogs/index.html.erb
<h1>Dogs#index</h1>
<p>Find me in app/views/dogs/index.html.erb</p>
<% @dogs.each do |dog| %>
  <h1><%= link_to dog.name,  dog_path(dog)%></h1>
  <h3><%= dog.motto %></h3>
<% end %>


<button type="button" name="button"><%= link_to 'New Dog', new_dog_path  %></button>

app/views/dogs/new.html.erb
<h1>Dogs#new</h1>
<p>Find me in app/views/dogs/new.html.erb</p>
<%= form_with model: @dog do |f| %>
  <%= f.text_field :name %>
  <%= f.text_field :motto %>
  <%= f.submit %>
<% end %>

app/views/dogs/show.html.erb
<h1>Dogs#show</h1>
<p>Find me in app/views/dogs/show.html.erb</p>
<h1><%= @dog.name %></h1>
<h2><%= @dog.motto %></h2>

<button type="button" name="button"><%= link_to 'Go back', dogs_path %></button>
<button type="button" name="button"><%= link_to 'Edit', edit_dog_path(@dog) %></button>
<button type="button" name="button"><%= link_to 'Delete', @dog, method: :delete, data: { confirm: 'Are you sure ?' } %></button>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>